---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: auth
  namespace: poseidon
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: glob:3.1.1-debian-9-*
spec:
  releaseName: auth
  chart:
    git: ssh://git@github.com/kylewu/flux-get-started
    ref: master
    path: charts/auth
  values:
    image:
      repository: 483413526957.dkr.ecr.us-east-1.amazonaws.com/auth
      pullPolicy: Always
    replicaCount: 1
    resources:
      requests:
        memory: 256Mi
        cpu: 10m