---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: loyalty
  namespace: poseidon
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: glob:3.1.1-debian-9-*
spec:
  releaseName: loyalty
  chart:
    git: ssh://git@github.com/kylewu/flux-get-started
    ref: master
    path: charts/demo
  values:
    fullnameOverride: loyalty
    image:
      repository: 483413526957.dkr.ecr.us-east-1.amazonaws.com/demo
    replicaCount: 1
    env:
      - name: PORT
        value: "3000"
      - name: MESSAGE
        value: "Loyalty Service"
      - name: API_PATH
        value: "/api/v1"

    resources:
      requests:
        memory: 256Mi
        cpu: 10m
    ingress:
      enabled: true
      annotations:
        # use the shared ingress-nginx
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/rewrite-target: /api/v1/$2
        nginx.ingress.kubernetes.io/auth-url: "http://auth-service.default.svc.cluster.local/auth"
        nginx.ingress.kubernetes.io/auth-cache-key: '$http_authorization$http_x_poseidon_enterprise_key$http_x_poseidon_client_id'
      hosts:
        - host:
          paths: ["/loyalty(/|$)(.*)"]